version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      n8n-manager:
        patterns:
          - "@n8n-as-code/n8n-manager*"
    commit-message:
      prefix: "fix"
      include: "scope"
