import { AiContextGenerator } from '../src/services/ai-context-generator.js';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';
import { execFileSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe('AiContextGenerator', () => {
    let tempDir: string;
    let generator: AiContextGenerator;

    beforeEach(() => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'n8n-ai-test-'));
        generator = new AiContextGenerator();
    });

    afterEach(() => {
        fs.rmSync(tempDir, { recursive: true, force: true });
    });

    describe('Context root bootstrap', () => {
        test('creates lightweight AGENTS.md and local skills on fresh install', async () => {
            const version = '1.0.0';
            await generator.generate(tempDir, version);

            const agentsPath = path.join(tempDir, 'AGENTS.md');
            const managerSkillPath = path.join(tempDir, '.agents/skills/n8n-manager/SKILL.md');
            const architectSkillPath = path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md');

            expect(fs.existsSync(agentsPath)).toBe(true);
            expect(fs.existsSync(managerSkillPath)).toBe(true);
            expect(fs.existsSync(architectSkillPath)).toBe(true);

            const agentsContent = fs.readFileSync(agentsPath, 'utf-8');
            expect(agentsContent).toContain('<!-- n8n-as-code-start -->');
            expect(agentsContent).toContain(`- n8n version at generation time: ${version}`);
            expect(agentsContent).toContain('This file is generated by');
            expect(agentsContent).toContain('.agents/skills/n8n-manager/SKILL.md');
            expect(agentsContent).toContain('.agents/skills/n8n-architect/SKILL.md');
            expect(agentsContent).toContain('n8n-manager plus n8nac backend resolution remains the only source');
            expect(agentsContent).toContain('workspace status --json');
            expect(agentsContent).toContain('npx --yes @n8n-as-code/n8n-manager');
            expect(agentsContent).toContain('Use the returned `workflowDir` exactly as provided.');
            expect(agentsContent).toContain('<!-- n8n-as-code-end -->');
        });

        test('uses matching published dist tags for portable n8nac and n8n-manager commands', async () => {
            await generator.generate(tempDir, '1.0.0', 'next');

            const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
            const managerSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-manager/SKILL.md'), 'utf-8');
            const architectSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf-8');

            expect(agentsContent).toContain('npx --yes n8nac@next workspace status --json');
            expect(agentsContent).toContain('npx --yes @n8n-as-code/n8n-manager@next ...');
            expect(managerSkill).toContain('npx --yes @n8n-as-code/n8n-manager@next instances list');
            expect(architectSkill).toContain('npx --yes @n8n-as-code/n8n-manager@next instances list');
        });

        test('updates existing n8n block without duplication', async () => {
            const agentsPath = path.join(tempDir, 'AGENTS.md');

            await generator.generate(tempDir, '1.0.0');
            const run1 = fs.readFileSync(agentsPath, 'utf-8');
            expect(run1).toContain('1.0.0');

            await generator.generate(tempDir, '2.0.0');
            const run2 = fs.readFileSync(agentsPath, 'utf-8');

            expect(run2).toContain('2.0.0');
            expect(run2).not.toContain('1.0.0');
            expect(run2.match(/<!-- n8n-as-code-start -->/g)?.length).toBe(1);
        });

        test('does not duplicate effective config values into AGENTS.md', async () => {
            await generator.generate(tempDir, '1.0.0');

            const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
            expect(agentsContent).not.toContain('Effective instance');
            expect(agentsContent).not.toContain('Active project');
            expect(agentsContent).not.toContain('Sync folder:');
            expect(agentsContent).not.toContain('Workspace-pinned instance');
        });

        test('allows overriding generated commands for local dev workspaces', async () => {
            const cliCmd = 'node /tmp/n8n-as-code/packages/cli/dist/index.js';
            const managerCmd = 'node /tmp/n8n-manager/packages/cli/dist/index.js';
            await generator.generate(tempDir, '1.0.0', undefined, {
                cliCommandOverride: cliCmd,
                managerCommandOverride: managerCmd,
            });

            const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
            const managerSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-manager/SKILL.md'), 'utf-8');
            const architectSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf-8');

            expect(agentsContent).toContain(cliCmd);
            expect(agentsContent).toContain(managerCmd);
            expect(managerSkill).toContain(managerCmd);
            expect(architectSkill).toContain(cliCmd);
            expect(architectSkill).toContain(`${cliCmd} skills`);
        });

        test('resolves generated CLI command from workspace dev config', async () => {
            const cliCmd = 'node /tmp/dev/n8n-as-code/packages/cli/dist/index.js';
            const previousEnvCommand = process.env.N8NAC_COMMAND;
            delete process.env.N8NAC_COMMAND;
            fs.writeFileSync(path.join(tempDir, '.n8nac-dev.json'), JSON.stringify({
                commands: { n8nac: cliCmd },
            }, null, 2));

            try {
                await generator.generate(tempDir, '1.0.0');

                const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
                const architectSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf-8');

                expect(agentsContent).toContain(cliCmd);
                expect(architectSkill).toContain(cliCmd);
                expect(architectSkill).not.toContain('{{N8NAC_CMD}}');
            } finally {
                if (previousEnvCommand === undefined) {
                    delete process.env.N8NAC_COMMAND;
                } else {
                    process.env.N8NAC_COMMAND = previousEnvCommand;
                }
            }
        });

        test('prefers N8NAC_COMMAND over workspace dev config', async () => {
            const envCmd = 'node /tmp/env/n8n-as-code/packages/cli/dist/index.js';
            const workspaceCmd = 'node /tmp/dev/n8n-as-code/packages/cli/dist/index.js';
            const previousEnvCommand = process.env.N8NAC_COMMAND;
            process.env.N8NAC_COMMAND = envCmd;
            fs.writeFileSync(path.join(tempDir, '.n8nac-dev.json'), JSON.stringify({
                commands: { n8nac: workspaceCmd },
            }, null, 2));

            try {
                await generator.generate(tempDir, '1.0.0');

                const agentsContent = fs.readFileSync(path.join(tempDir, 'AGENTS.md'), 'utf-8');
                const architectSkill = fs.readFileSync(path.join(tempDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf-8');

                expect(agentsContent).toContain(envCmd);
                expect(agentsContent).not.toContain(workspaceCmd);
                expect(architectSkill).toContain(envCmd);
                expect(architectSkill).not.toContain(workspaceCmd);
            } finally {
                if (previousEnvCommand === undefined) {
                    delete process.env.N8NAC_COMMAND;
                } else {
                    process.env.N8NAC_COMMAND = previousEnvCommand;
                }
            }
        });

        test('does not create legacy shim files', async () => {
            await generator.generate(tempDir, '1.0.0');

            expect(fs.existsSync(path.join(tempDir, 'n8nac-skills'))).toBe(false);
            expect(fs.existsSync(path.join(tempDir, 'n8nac-skills.cmd'))).toBe(false);
            expect(fs.existsSync(path.join(tempDir, 'n8nac'))).toBe(false);
            expect(fs.existsSync(path.join(tempDir, 'n8nac.cmd'))).toBe(false);
        });
    });

    describe('Canonical skills', () => {
        test('n8n-manager skill contains runtime/auth guardrails', () => {
            const content = generator.getAgentSkillContent('n8n-manager');

            expect(content).toContain('managed-local-docker');
            expect(content).toContain('--api-key-stdin');
            expect(content).toContain('Do not ask for host/API key before checking');
            expect(content).toContain('presentWorkflowResult');
            expect(content).not.toContain('{{N8N_MANAGER_CMD}}');
        });

        test('n8n-architect skill contains workflow and schema-first guidance', () => {
            const content = generator.getAgentSkillContent('n8n-architect');

            expect(content).toContain('workspace status --json');
            expect(content).toContain('workflowDir');
            expect(content).toContain('node-info <nodeName>');
            expect(content).toContain('ai_tool: [this.Tool.output]');
            expect(content).toContain('Reading Workflow Files Efficiently');
            expect(content).toContain('Common Mistakes To Avoid');
            expect(content).toContain('Credential Workflow');
            expect(content).toContain('Execution Debugging');
            expect(content).toContain('Operating Loop');
            expect(content).toContain('Workflow Presentation Contract');
            expect(content).toContain('Do not manually construct n8n workflow URLs');
            expect(content).toContain('presentWorkflowResult');
            expect(content).not.toContain('{{N8NAC_CMD}}');
        });

        test('legacy OpenClaw-specific skill generator returns the canonical architect skill', () => {
            expect(generator.getOpenClawSkillContent()).toBe(generator.getSkillContent());
            expect(generator.getOpenClawSkillContent()).not.toContain('action: "skills"');
        });

        test('packaged plugin skills do not diverge from canonical generated skills', () => {
            const repoRoot = path.resolve(__dirname, '../../..');
            const pluginSkillRoots = [
                path.join(repoRoot, 'plugins/claude/n8n-as-code/skills'),
                path.join(repoRoot, 'plugins/openclaw/n8n-as-code/skills'),
                path.join(repoRoot, 'plugins/cursor/n8n-as-code/skills'),
            ];
            const distTag = resolveAdapterDistTag(repoRoot);

            for (const pluginRoot of pluginSkillRoots) {
                const expected = {
                    'n8n-manager': generator.getAgentSkillContent('n8n-manager', distTag),
                    'n8n-architect': generator.getAgentSkillContent('n8n-architect', distTag),
                };
                for (const skillName of Object.keys(expected) as Array<keyof typeof expected>) {
                    const skillPath = path.join(pluginRoot, skillName, 'SKILL.md');
                    expect(fs.existsSync(skillPath)).toBe(true);
                    expect(fs.readFileSync(skillPath, 'utf8')).toBe(expected[skillName]);
                }
            }
        });
    });
});

function resolveAdapterDistTag(repoRoot: string): string | undefined {
    const explicit = process.env.N8NAC_SKILL_ADAPTER_DIST_TAG?.trim();
    if (explicit) {
        return ['stable', 'latest', 'none'].includes(explicit) ? undefined : explicit;
    }

    if (process.env.GITHUB_BASE_REF === 'main') {
        return undefined;
    }

    const versions = [
        path.join(repoRoot, 'packages/cli/package.json'),
        path.join(repoRoot, 'packages/skills/package.json'),
    ].map((packagePath) => JSON.parse(fs.readFileSync(packagePath, 'utf8')).version as string);

    if (versions.some((version) => version.includes('-next'))) {
        return 'next';
    }

    const branch = process.env.GITHUB_REF_NAME || process.env.BRANCH_NAME || readGitBranch(repoRoot);
    return branch === 'next' ? 'next' : undefined;
}

function readGitBranch(repoRoot: string): string | undefined {
    try {
        return execFileSync('git', ['branch', '--show-current'], {
            cwd: repoRoot,
            encoding: 'utf8',
            stdio: ['ignore', 'pipe', 'ignore'],
        }).trim();
    } catch {
        return undefined;
    }
}
