import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';

const tempDirs: string[] = [];
const repoRoot = path.resolve(import.meta.dirname, '../../../..');
const cliEntry = path.join(repoRoot, 'packages/cli/dist/index.js');
const cliVersion: string = JSON.parse(
    readFileSync(path.join(repoRoot, 'packages/cli/package.json'), 'utf8')
).version;

function createTempDir(prefix: string): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
    tempDirs.push(dir);
    return dir;
}

const baseEnv = { ...process.env, N8N_HOST: '', N8N_API_KEY: '' };

function runUpdateAi(workspaceDir: string, extraArgs: string[] = [], envOverrides: NodeJS.ProcessEnv = {}): string {
    return execFileSync('node', [cliEntry, 'update-ai', '--cli-cmd', `node ${cliEntry}`, ...extraArgs], {
        cwd: workspaceDir,
        env: {
            ...baseEnv,
            N8N_MANAGER_HOME: createTempDir('n8nac-update-ai-manager-home-'),
            ...envOverrides,
        },
        stdio: 'pipe',
        encoding: 'utf8',
    });
}

function runCli(workspaceDir: string, args: string[], envOverrides: NodeJS.ProcessEnv = {}): string {
    return execFileSync('node', [cliEntry, ...args], {
        cwd: workspaceDir,
        env: {
            ...baseEnv,
            N8N_MANAGER_HOME: createTempDir('n8nac-cli-manager-home-'),
            ...envOverrides,
        },
        stdio: 'pipe',
        encoding: 'utf8',
    });
}

function runCliFailure(workspaceDir: string, args: string[], envOverrides: NodeJS.ProcessEnv = {}): { status: number | null; stdout: string; stderr: string } {
    try {
        execFileSync('node', [cliEntry, ...args], {
            cwd: workspaceDir,
            env: {
                ...baseEnv,
                N8N_MANAGER_HOME: createTempDir('n8nac-cli-manager-home-'),
                ...envOverrides,
            },
            stdio: 'pipe',
            encoding: 'utf8',
        });
        throw new Error('Expected command to fail.');
    } catch (error: any) {
        if (error.message === 'Expected command to fail.') throw error;
        return {
            status: typeof error.status === 'number' ? error.status : null,
            stdout: String(error.stdout || ''),
            stderr: String(error.stderr || ''),
        };
    }
}

beforeAll(() => {
    execFileSync('npm', ['run', 'build', '--workspace=packages/cli'], {
        cwd: repoRoot,
        stdio: 'pipe',
        encoding: 'utf8',
    });
});

afterAll(() => {
    for (const dir of tempDirs) {
        fs.rmSync(dir, { recursive: true, force: true });
    }
});

describe('CLI update-ai integration', () => {
    it('generates lightweight AGENTS.md, VS Code agents, and portable local skills', () => {
        const workspaceDir = createTempDir('n8nac-update-ai-workspace-');
        runUpdateAi(workspaceDir);

        const agentsPath = path.join(workspaceDir, 'AGENTS.md');
        const architectAgentPath = path.join(workspaceDir, '.github/agents/n8n-architect.agent.md');
        const architectSkillPath = path.join(workspaceDir, '.agents/skills/n8n-architect/SKILL.md');
        expect(fs.existsSync(agentsPath)).toBe(true);
        expect(fs.existsSync(architectAgentPath)).toBe(true);
        expect(fs.existsSync(architectSkillPath)).toBe(true);

        const agentsContent = fs.readFileSync(agentsPath, 'utf8');
        const architectSkill = fs.readFileSync(architectSkillPath, 'utf8');

        expect(agentsContent).toContain('This file is generated by');
        expect(agentsContent).toContain('Do not infer configuration from this file');
        expect(agentsContent).toContain(`node ${cliEntry} workspace status --json`);
        expect(agentsContent).toContain(`node ${cliEntry} workspace migrate --json`);
        expect(agentsContent.indexOf(`node ${cliEntry} workspace migrate --json`)).toBeLessThan(agentsContent.indexOf(`node ${cliEntry} workspace status --json`));
        expect(agentsContent).toContain('.github/agents/n8n-architect.agent.md');
        expect(agentsContent).toContain('.agents/skills/n8n-architect/SKILL.md');
        expect(agentsContent).not.toContain('.github/agents/n8n-manager.agent.md');
        expect(agentsContent).not.toContain('.agents/skills/n8n-manager/SKILL.md');
        expect(agentsContent).not.toContain('Effective instance');
        expect(agentsContent).not.toContain('Active project');
        expect(architectSkill).toContain(`node ${cliEntry} workspace status --json`);
        expect(architectSkill).toContain(`node ${cliEntry} workspace migrate --json`);
        expect(architectSkill).toContain('Never chain readiness commands as');
        expect(architectSkill.indexOf(`node ${cliEntry} workspace migrate --json`)).toBeLessThan(architectSkill.indexOf(`node ${cliEntry} workspace status --json`));
        expect(architectSkill).toContain(`node ${cliEntry} env add Local --managed-instance <id> --sync-folder workflows/local`);
        expect(architectSkill).toContain('Managed Local Runtime');
        expect(architectSkill).toContain('--api-key-stdin');
        expect(agentsContent).not.toContain('saved instance configs');
    });

    it('embeds the n8nac CLI version stamp in AGENTS.md', () => {
        const workspaceDir = createTempDir('n8nac-update-ai-stamp-');
        runUpdateAi(workspaceDir);

        const agentsContent = fs.readFileSync(path.join(workspaceDir, 'AGENTS.md'), 'utf8');
        expect(agentsContent).toContain(`<!-- n8nac-version: ${cliVersion} -->`);
    });

    it('reports a unified migration dry-run from workspace status for legacy configs', () => {
        const workspaceDir = createTempDir('n8nac-status-legacy-workspace-');
        fs.writeFileSync(path.join(workspaceDir, 'n8nac-config.json'), JSON.stringify({
            version: 2,
            activeInstanceId: 'legacy-prod',
            instances: [{
                id: 'legacy-prod',
                name: 'Legacy Prod',
                host: 'https://legacy.example.test',
            }],
        }, null, 2));

        const output = runCli(workspaceDir, ['workspace', 'status', '--json']);
        const payload = JSON.parse(output);

        expect(payload).toMatchObject({
            status: 'dry-run',
            required: true,
            nextCommand: 'n8nac workspace migrate --json',
            applyCommand: 'n8nac workspace migrate --write',
        });
        expect(payload).not.toHaveProperty('migration');
        expect(payload.operations[0]).toMatchObject({
            id: 'legacy-workspace-config',
            label: 'Legacy workspace config',
            instanceCount: 1,
        });
        expect(payload.operations[0].instances[0]).toMatchObject({
            id: 'legacy-prod',
            name: 'Legacy Prod',
            kind: 'legacy-workspace-instance',
        });
    });

    it('blocks environment commands while workspace migration is pending', () => {
        const workspaceDir = createTempDir('n8nac-env-blocked-legacy-workspace-');
        fs.writeFileSync(path.join(workspaceDir, 'n8nac-config.json'), JSON.stringify({
            version: 2,
            activeInstanceId: 'legacy-prod',
            instances: [{
                id: 'legacy-prod',
                name: 'Legacy Prod',
                host: 'https://legacy.example.test',
            }],
        }, null, 2));

        const result = runCliFailure(workspaceDir, ['env', 'list', '--json']);
        const payload = JSON.parse(result.stdout);

        expect(result.status).toBe(1);
        expect(payload).toMatchObject({
            status: 'dry-run',
            required: true,
            nextCommand: 'n8nac workspace migrate --json',
            applyCommand: 'n8nac workspace migrate --write',
        });
    });

    it('uses n8nac workflow presentation and keeps n8n-manager guidance limited', () => {
        const workspaceDir = createTempDir('n8nac-update-ai-manager-tools-');
        const managerCmd = 'node /tmp/n8n-manager.js';
        runUpdateAi(workspaceDir, ['--manager-cmd', managerCmd]);

        const agentsContent = fs.readFileSync(path.join(workspaceDir, 'AGENTS.md'), 'utf8');
        const architectAgent = fs.readFileSync(path.join(workspaceDir, '.github/agents/n8n-architect.agent.md'), 'utf8');
        const architectSkill = fs.readFileSync(path.join(workspaceDir, '.agents/skills/n8n-architect/SKILL.md'), 'utf8');
        expect(agentsContent).not.toContain('<!-- n8n-manager-agent-tools-start -->');
        expect(architectAgent).toContain(`node ${cliEntry} workflow present <workflowId> --json`);
        expect(architectSkill).toContain(`node ${cliEntry} workflow present <workflowId> --json`);
        expect(architectAgent).toContain(`Do not call \`${managerCmd} presentWorkflowResult\``);
        expect(architectSkill).toContain(`Do not call \`${managerCmd} presentWorkflowResult\``);
        expect(fs.existsSync(path.join(workspaceDir, '.github/agents/n8n-manager.agent.md'))).toBe(false);
        expect(fs.existsSync(path.join(workspaceDir, '.agents/skills/n8n-manager/SKILL.md'))).toBe(false);
    });

    it('checkAndRefreshIfStale silently refreshes AGENTS.md when the version stamp is stale', async () => {
        const workspaceDir = createTempDir('n8nac-update-ai-stale-');

        // Seed AGENTS.md with a fake old version stamp
        const agentsPath = path.join(workspaceDir, 'AGENTS.md');
        fs.writeFileSync(agentsPath, [
            '# 🤖 AI Agents Guidelines',
            '<!-- n8n-as-code-start -->',
            '<!-- n8nac-version: 0.0.1 -->',
            '## old content',
            '<!-- n8n-as-code-end -->',
        ].join('\n'), 'utf8');

        // Call checkAndRefreshIfStale directly — this exercises the actual stale-detection
        // logic rather than just running update-ai (which always regenerates unconditionally).
        const updateAiDistPath = path.join(repoRoot, 'packages/cli/dist/commands/update-ai.js');
        const { UpdateAiCommand } = await import(updateAiDistPath) as typeof import('../../src/commands/update-ai.js');
        await UpdateAiCommand.checkAndRefreshIfStale(workspaceDir);

        const refreshed = fs.readFileSync(agentsPath, 'utf8');
        // Stamp must now match the current version
        expect(refreshed).toContain(`<!-- n8nac-version: ${cliVersion} -->`);
        // Content must be a full lightweight AGENTS.md (not just "old content")
        expect(refreshed).toContain('n8n-as-code Context Root');
        expect(refreshed).toContain('workspace status --json');
        expect(fs.existsSync(path.join(workspaceDir, '.github/agents/n8n-architect.agent.md'))).toBe(true);
        expect(fs.existsSync(path.join(workspaceDir, '.agents/skills/n8n-architect/SKILL.md'))).toBe(true);
    });

    it('refreshes n8n-workflows.d.ts for all configured instance directories', () => {
        const workspaceDir = createTempDir('n8nac-update-ai-dts-');

        const instanceIdentifier = 'n8n_c6c289e49e';
        const syncFolder = 'workflows';
        const projectName = 'My Project';
        const projectSlug = 'my_project';
        const managerHome = createTempDir('n8nac-update-ai-dts-manager-home-');

        const instanceDir = path.join(workspaceDir, syncFolder, instanceIdentifier, projectSlug);
        fs.mkdirSync(instanceDir, { recursive: true });

        const dtsPath = path.join(instanceDir, 'n8n-workflows.d.ts');
        fs.writeFileSync(dtsPath, '// stale', 'utf8');

        fs.writeFileSync(
            path.join(managerHome, 'instances.json'),
            JSON.stringify({
                version: 1,
                activeInstanceId: 'inst-1',
                defaultSyncFolder: 'workflows',
                instances: [{
                    id: 'inst-1',
                    name: 'Test Instance',
                    mode: 'existing',
                    baseUrl: 'http://localhost:5678',
                    instanceIdentifier,
                    defaultProject: {
                        id: 'proj-1',
                        name: projectName,
                    },
                }],
            }, null, 2),
            'utf8'
        );

        const config = {
            version: 3,
            activeInstanceId: 'inst-1',
            syncFolder,
            projectId: 'proj-1',
            projectName,
        };
        fs.writeFileSync(
            path.join(workspaceDir, 'n8nac-config.json'),
            JSON.stringify(config, null, 2),
            'utf8'
        );

        runUpdateAi(workspaceDir, [], { N8N_MANAGER_HOME: managerHome });

        expect(fs.existsSync(dtsPath)).toBe(true);
        const dtsContent = fs.readFileSync(dtsPath, 'utf8');
        expect(dtsContent).not.toBe('// stale');
        expect(dtsContent.length).toBeGreaterThan(100);
    });
});
