import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';

const tempDirs: string[] = [];
const repoRoot = path.resolve(import.meta.dirname, '../../../..');
const cliEntry = path.join(repoRoot, 'packages/cli/dist/index.js');
const cliVersion: string = JSON.parse(
    readFileSync(path.join(repoRoot, 'packages/cli/package.json'), 'utf8')
).version;

function createTempDir(prefix: string): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
    tempDirs.push(dir);
    return dir;
}

const baseEnv = { ...process.env, N8N_HOST: '', N8N_API_KEY: '' };

function runUpdateAi(workspaceDir: string, extraArgs: string[] = [], envOverrides: NodeJS.ProcessEnv = {}): string {
    return execFileSync('node', [cliEntry, 'update-ai', '--cli-cmd', `node ${cliEntry}`, ...extraArgs], {
        cwd: workspaceDir,
        env: {
            ...baseEnv,
            N8N_MANAGER_HOME: createTempDir('n8nac-update-ai-manager-home-'),
            ...envOverrides,
        },
        stdio: 'pipe',
        encoding: 'utf8',
    });
}

beforeAll(() => {
    execFileSync('npm', ['run', 'build', '--workspace=packages/cli'], {
        cwd: repoRoot,
        stdio: 'pipe',
        encoding: 'utf8',
    });
});

afterAll(() => {
    for (const dir of tempDirs) {
        fs.rmSync(dir, { recursive: true, force: true });
    }
});

describe('CLI update-ai integration', () => {
    it('generates lightweight AGENTS.md, VS Code agents, and portable local skills', () => {
        const workspaceDir = createTempDir('n8nac-update-ai-workspace-');
        runUpdateAi(workspaceDir);

        const agentsPath = path.join(workspaceDir, 'AGENTS.md');
        const managerAgentPath = path.join(workspaceDir, '.github/agents/n8n-manager.agent.md');
        const architectAgentPath = path.join(workspaceDir, '.github/agents/n8n-architect.agent.md');
        const managerSkillPath = path.join(workspaceDir, '.agents/skills/n8n-manager/SKILL.md');
        const architectSkillPath = path.join(workspaceDir, '.agents/skills/n8n-architect/SKILL.md');
        expect(fs.existsSync(agentsPath)).toBe(true);
        expect(fs.existsSync(managerAgentPath)).toBe(true);
        expect(fs.existsSync(architectAgentPath)).toBe(true);
        expect(fs.existsSync(managerSkillPath)).toBe(true);
        expect(fs.existsSync(architectSkillPath)).toBe(true);

        const agentsContent = fs.readFileSync(agentsPath, 'utf8');
        const managerAgent = fs.readFileSync(managerAgentPath, 'utf8');
        const managerSkill = fs.readFileSync(managerSkillPath, 'utf8');
        const architectSkill = fs.readFileSync(architectSkillPath, 'utf8');

        expect(agentsContent).toContain('This file is generated by');
        expect(agentsContent).toContain('Do not infer configuration from this file');
        expect(agentsContent).toContain(`node ${cliEntry} workspace status --json`);
        expect(agentsContent).toContain('.github/agents/n8n-manager.agent.md');
        expect(agentsContent).toContain('.agents/skills/n8n-manager/SKILL.md');
        expect(agentsContent).not.toContain('Effective instance');
        expect(agentsContent).not.toContain('Active project');
        expect(managerAgent).toContain('Use this workspace agent for global n8n instance management.');
        expect(managerSkill).toContain('managed-local-docker');
        expect(managerSkill).toContain('--api-key-stdin');
        expect(architectSkill).toContain(`node ${cliEntry} workspace status --json`);
        expect(architectSkill).toContain(`node ${cliEntry} workspace set-sync-folder workflows`);
        expect(agentsContent).not.toContain('saved instance configs');
    });

    it('embeds the n8nac CLI version stamp in AGENTS.md', () => {
        const workspaceDir = createTempDir('n8nac-update-ai-stamp-');
        runUpdateAi(workspaceDir);

        const agentsContent = fs.readFileSync(path.join(workspaceDir, 'AGENTS.md'), 'utf8');
        expect(agentsContent).toContain(`<!-- n8nac-version: ${cliVersion} -->`);
    });

    it('places n8n-manager agent tooling instructions in the local skill, not AGENTS.md', () => {
        const workspaceDir = createTempDir('n8nac-update-ai-manager-tools-');
        const managerCmd = 'node /tmp/n8n-manager.js';
        runUpdateAi(workspaceDir, ['--manager-cmd', managerCmd]);

        const agentsContent = fs.readFileSync(path.join(workspaceDir, 'AGENTS.md'), 'utf8');
        const managerAgent = fs.readFileSync(path.join(workspaceDir, '.github/agents/n8n-manager.agent.md'), 'utf8');
        const managerSkill = fs.readFileSync(path.join(workspaceDir, '.agents/skills/n8n-manager/SKILL.md'), 'utf8');
        expect(agentsContent).not.toContain('<!-- n8n-manager-agent-tools-start -->');
        expect(managerAgent).toContain(`${managerCmd} presentWorkflowResult --workflow-id <workflowId> --workspace-root <contextRoot>`);
        expect(managerSkill).toContain(`${managerCmd} presentWorkflowResult --workflow-id <workflowId> --workspace-root <contextRoot>`);
    });

    it('checkAndRefreshIfStale silently refreshes AGENTS.md when the version stamp is stale', async () => {
        const workspaceDir = createTempDir('n8nac-update-ai-stale-');

        // Seed AGENTS.md with a fake old version stamp
        const agentsPath = path.join(workspaceDir, 'AGENTS.md');
        fs.writeFileSync(agentsPath, [
            '# 🤖 AI Agents Guidelines',
            '<!-- n8n-as-code-start -->',
            '<!-- n8nac-version: 0.0.1 -->',
            '## old content',
            '<!-- n8n-as-code-end -->',
        ].join('\n'), 'utf8');

        // Call checkAndRefreshIfStale directly — this exercises the actual stale-detection
        // logic rather than just running update-ai (which always regenerates unconditionally).
        const updateAiDistPath = path.join(repoRoot, 'packages/cli/dist/commands/update-ai.js');
        const { UpdateAiCommand } = await import(updateAiDistPath) as typeof import('../../src/commands/update-ai.js');
        await UpdateAiCommand.checkAndRefreshIfStale(workspaceDir);

        const refreshed = fs.readFileSync(agentsPath, 'utf8');
        // Stamp must now match the current version
        expect(refreshed).toContain(`<!-- n8nac-version: ${cliVersion} -->`);
        // Content must be a full lightweight AGENTS.md (not just "old content")
        expect(refreshed).toContain('n8n-as-code Context Root');
        expect(refreshed).toContain('workspace status --json');
        expect(fs.existsSync(path.join(workspaceDir, '.github/agents/n8n-architect.agent.md'))).toBe(true);
        expect(fs.existsSync(path.join(workspaceDir, '.agents/skills/n8n-architect/SKILL.md'))).toBe(true);
    });

    it('refreshes n8n-workflows.d.ts for all configured instance directories', () => {
        const workspaceDir = createTempDir('n8nac-update-ai-dts-');

        const instanceIdentifier = 'n8n_c6c289e49e';
        const syncFolder = 'workflows';
        const projectName = 'My Project';
        const projectSlug = 'my_project';
        const managerHome = createTempDir('n8nac-update-ai-dts-manager-home-');

        const instanceDir = path.join(workspaceDir, syncFolder, instanceIdentifier, projectSlug);
        fs.mkdirSync(instanceDir, { recursive: true });

        const dtsPath = path.join(instanceDir, 'n8n-workflows.d.ts');
        fs.writeFileSync(dtsPath, '// stale', 'utf8');

        fs.writeFileSync(
            path.join(managerHome, 'instances.json'),
            JSON.stringify({
                version: 1,
                activeInstanceId: 'inst-1',
                defaultSyncFolder: 'workflows',
                instances: [{
                    id: 'inst-1',
                    name: 'Test Instance',
                    mode: 'existing',
                    baseUrl: 'http://localhost:5678',
                    instanceIdentifier,
                    defaultProject: {
                        id: 'proj-1',
                        name: projectName,
                    },
                }],
            }, null, 2),
            'utf8'
        );

        const config = {
            version: 3,
            activeInstanceId: 'inst-1',
            syncFolder,
            projectId: 'proj-1',
            projectName,
        };
        fs.writeFileSync(
            path.join(workspaceDir, 'n8nac-config.json'),
            JSON.stringify(config, null, 2),
            'utf8'
        );

        runUpdateAi(workspaceDir, [], { N8N_MANAGER_HOME: managerHome });

        expect(fs.existsSync(dtsPath)).toBe(true);
        const dtsContent = fs.readFileSync(dtsPath, 'utf8');
        expect(dtsContent).not.toBe('// stale');
        expect(dtsContent.length).toBeGreaterThan(100);
    });
});
